name: Release New Version

on:
  push:
    branches:
      - main

env:
  GITHUB_TOKEN: ${{ secrets.GOPKG_GITHUB_TOKEN }}

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - id: new_tag
        name: Generate release version
        uses: gandarez/semver-action@master
        with:
          branching_model: "git-flow"
          prefix: "v"
          main_branch_name: "main"
          patch_regex: "^fix/.+"
          minor_regex: "^feat/.+"
          major_regex: "^major/.+"
          hotfix_regex: "^hotfix/.+"

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ env.GITHUB_TOKEN }}

      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.new_tag.outputs.semver_tag }}
          name: Release ${{ steps.ne4w_tag.outputs.semver_tag }}